apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  labels:
    app: user-service
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:mysql://polar-mysql:3306/movie_db